### ISSUE TITLE
A critical error occurred when trying to activate the license key using Studio by WordPress.com on macOS.

### ISSUE THREAD

**Issue by faisalahammad** [fluentform/fluentform#416]
I'm using **Studio by WordPress.com** `v1.0.2` on macOS `v14.4.1`. When I try to activate the license key, I encounter the following error. Upon returning to the dashboard, everything functions correctly, and I can still access the license page, but the license is still not there. If I attempt to activate it again, the same issue occurs.

`Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php on line 350`

`Warning: file_get_contents(https://apiv2.wpmanageninja.com/plugin?edd_action=activate_license&license=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&item_name=&item_id=542&url=http%3A%2F%2Flocalhost%3A8882): Failed to open stream: no suitable wrapper could be found in /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php on line 350`

`Fatal error: Uncaught Error: Call to undefined function curl_init() in /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php:587 Stack trace: #0 /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php(352): FluentFormAddOnChecker->urlGetContentFallBack('https://apiv2.w...') #1 /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php(299): FluentFormAddOnChecker->tryActivateLicense('45694cadcdde9eb...') #2 /var/www/html/wp-includes/class-wp-hook.php(324): FluentFormAddOnChecker->activate_license('') #3 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) #4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /var/www/html/wp-admin/admin.php(175): do_action('admin_init') #6 /var/www/html/wp-admin/options.php(19): require_once('/var/www/html/w...') #7 {main} thrown in /var/www/html/wp-content/plugins/fluentformpro/libs/ff_plugin_updater/updater/FluentFormAddOnChecker.php on line 587`

**Screenshot:**

![Critical Error@2x](https://github.com/fluentform/fluentform/assets/13257516/b23c00ce-63a3-4e39-baa0-481be4b3ee56)

**Comment by HrDelwar** [comment]
@faisalahammad The error suggests that the allow_url_fopen directive is disabled and the curl_init function is unavailable in the PHP configuration on your server setup. Try to enable allow_url_fopen this can be done by editing the php.ini file and setting allow_url_fopen = On, then restarting the server. Also ensure that the cURL extension is installed and enabled in PHP.

**Comment by faisalahammad** [comment]
Thank you @HrDelwar 

Actually Studio by WordPress.com doesn't allow to select PHP version or modify the configuration. I'll report this to the Studio's GH issues page. Have a good day!

**Comment by HrDelwar** [comment]
@faisalahammad As identified in the discussion, this appears to be related to PHP configuration limitations in Studio by WordPress.com, specifically disabled allow_url_fopen and missing cURL support. These are requirements for our license activation process. Since Studio by WordPress.com doesn't allow modifying PHP configurations, and you've mentioned you'll report this to their GitHub issues page, I'm closing this issue here.

If you need any additional assistance with FluentForm in other environments, please don't hesitate to open a [support ticket](https://support.wpmanageninja.com/#/tickets).
